services:
  vllm-gen:
    build: .                      # builds from the Dockerfile above
    runtime: nvidia
    ipc: host
    # shm_size: 16gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ~/.cache:/.cache/
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/models"]
      interval: 30s
      retries: 5
      start_period: 240s